export const FETCH_FACTORIAL_NUMBER = 'FETCH_FACTORIAL_NUMBER';
export const FETCH_FACTORIAL_FAIL = 'FETCH_FACTORIAL_FAIL';
export const FETCH_FIBONACCI_NUMBER = 'FETCH_FIBONACCI_NUMBER';
export const FETCH_FIBONACCI_FAIL = 'FETCH_FIBONACCI_FAIL';
export const FETCH_PRIME_NUMBER = 'FETCH_PRIME_NUMBER';
export const FETCH_PRIME_FAIL = 'FETCH_PRIME_FAIL';
export const FETCH_RANGE_NUMBER = 'FETCH_RANGE_NUMBER';
export const FETCH_RANGE_FAIL = 'FETCH_RANGE_FAIL';